/home/athena/CLionProjects/temp/small/r0
/home/athena/CLionProjects/temp/small/r1
/home/athena/CLionProjects/temp/small/r2
/home/athena/CLionProjects/temp/small/r3
/home/athena/CLionProjects/temp/small/r4
/home/athena/CLionProjects/temp/small/r5
/home/athena/CLionProjects/temp/small/r6
/home/athena/CLionProjects/temp/small/r7
/home/athena/CLionProjects/temp/small/r8
/home/athena/CLionProjects/temp/small/r9
/home/athena/CLionProjects/temp/small/r10
/home/athena/CLionProjects/temp/small/r11
/home/athena/CLionProjects/temp/small/r12
/home/athena/CLionProjects/temp/small/r13

